#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/graphite-ch" ] || [ -e "/etc/init/#SCRIPT#.conf" ]; then
	invoke-rc.d graphite-ch stop || exit $?
fi
# End automatically added section
